# Port configurations for Cursed Proxy
# Format: <PORT>: <REGEX>

# Drop any packet on 1234 containing "david"
1234: .*david.*
8080: .*malicious_payload.*

# Drop any packet on 9000 containing more than 8 'A' characters consecutively
9000: .*A{9,}.*
